local:
    resource: "@LocalBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /

partage:
    resource: "@PartageBundle/Resources/config/routing.yml"
    prefix:   /

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /
